### ISSUE TITLE
Milestone 1, review 1: model + general coding hints

### ISSUE THREAD

**Issue by duman190** [googleinterns/minimal-wcmp-precision-loss#1]
- [Maybe use std::to_string(int, double, long, etc) here?](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/621714382d4259041f6f9ce90b3e525fd674287f/wcmp/main.h#L26)

- [/s/16000/16384 to be precise:)](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/621714382d4259041f6f9ce90b3e525fd674287f/wcmp/main.h#L17)

- [Avoid using new and delete operators here and everywhere as their use can lead to memory leaks.](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/621714382d4259041f6f9ce90b3e525fd674287f/wcmp/main.cpp#L28) Please, use:
-- either: DCNOnlyTopolgy network; and pass it by reference, 
-- or unique pointer: auto network_ptr = std::make_unique<DCNOnlyTopology>(); 

- [Maybe consider using logs here?](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/621714382d4259041f6f9ce90b3e525fd674287f/wcmp/main.cpp#L34)

- [Consider moving all vars to private and add get methods to access/modify them in all classes.](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/621714382d4259041f6f9ce90b3e525fd674287f/wcmp/components/Link.h#L19) For example:
-- Switch* mutable_src() { return src_; }  // To access and modify src_.
-- const Switch& src() { return *src_; }  // To access src_. No modification is allowed.

- [This is to quickly check upon LP construction if link belongs to some path, right?](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/621714382d4259041f6f9ce90b3e525fd674287f/wcmp/components/Link.h#L24) If so, consider use std::unordered_set or absl::flat_hash_set instead for a constant access time. Also, maybe path index (int) is sufficient to do this check?

- [nit: it won't accelerate calculation, but reduce time complexity of LP construction :)](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/621714382d4259041f6f9ce90b3e525fd674287f/wcmp/components/Path.h#L39)

- [Consider using map from src->dst to amount of traffic.](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/621714382d4259041f6f9ce90b3e525fd674287f/wcmp/topology/dcnonly/DCNOnlyTopology.h#L27) Common candidates are: std::unordered_map or absl::flat_hash_map.

- [IMO, topology should be the only owner for all switch, link and path objects.](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/621714382d4259041f6f9ce90b3e525fd674287f/wcmp/topology/dcnonly/DCNOnlyTopology.h#L28) Please, avoid using pointers here.

- [In general, please consider refactoring gigantic functions into smaller ones.](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/621714382d4259041f6f9ce90b3e525fd674287f/wcmp/topology/dcnonly/DCNOnlyTopology.cpp#L13) In this case, why not use private functions to generate all individual network element types: s1-s3 switches, links and paths?

- [Complexity of finding all direct DCN paths is O(SB_num * SB_num * SB_num * SB_num * 4 * S3_per_MB).](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/621714382d4259041f6f9ce90b3e525fd674287f/wcmp/topology/dcnonly/DCNOnlyTopology.cpp#L103) I would suggest revising data structures used. Ideally, we want intially to solve only for SB->SB level. So complexity of finding all 1 hop DCN paths should be O(SB_num^2), and complexity of finding all 2 hop paths should be O(SB_num^3).

- [Please, refactor this method.](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/621714382d4259041f6f9ce90b3e525fd674287f/wcmp/topology/dcnonly/DCNOnlyTopology.cpp#L153) Consider one function to create every var, constraint, etc.

- Maybe also add some experiment or data folder where you can commit data + plots of simulation results? I would suggest do a first set of tests considering time to solution based on number of SBs in the network.

**Comment by Clark5** [comment]
> Maybe use std::to_string(int, double, long, etc) here?

Changed to std::tostring().

> /s/16000/16384 to be precise:)

[Changed.](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/2c6c5d6ba61cea9cd1cae8c4acec48759b0cc2aa/wcmp/definitions.h#L20)

> Avoid using new and delete operators here and everywhere as their use can lead to memory leaks. Please, use:
> -- either: DCNOnlyTopolgy network; and pass it by reference,
> -- or unique pointer: auto network_ptr = std::make_unique();

[Removed all "new" operations.](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/2c6c5d6ba61cea9cd1cae8c4acec48759b0cc2aa/wcmp/main.cpp#L16)

> Maybe consider using logs here?

[Glog Added.](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/2c6c5d6ba61cea9cd1cae8c4acec48759b0cc2aa/wcmp/main.cpp#L20)

> Consider moving all vars to private and add get methods to access/modify them in all classes. For example:
> -- Switch* mutable_src() { return src_; } // To access and modify src_.
> -- const Switch& src() { return *src_; } // To access src_. No modification is allowed.

[Changed the class into a struct](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/2c6c5d6ba61cea9cd1cae8c4acec48759b0cc2aa/wcmp/definitions.h#L30), let all variables to be public.

> This is to quickly check upon LP construction if link belongs to some path, right? If so, consider use std::unordered_set or absl::flat_hash_set instead for a constant access time. Also, maybe path index (int) is sufficient to do this check?

The [current design](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/2c6c5d6ba61cea9cd1cae8c4acec48759b0cc2aa/wcmp/topology/dcnonly/DCNOnlyTopology.h#L38) is optimized for the "for" loop during SCIP construction. If we need to fetch one path from the set in the future, I will add the unordered_set.

> nit: it won't accelerate calculation, but reduce time complexity of LP construction :)

Comments changed. File deleted. 

> Consider using map from src->dst to amount of traffic. Common candidates are: std::unordered_map or absl::flat_hash_map.

[Changed into std::unordered_map.](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/2c6c5d6ba61cea9cd1cae8c4acec48759b0cc2aa/wcmp/topology/dcnonly/DCNOnlyTopology.h#L29)

> IMO, topology should be the only owner for all switch, link and path objects. Please, avoid using pointers here.

All the switch, link, and path object now [only owned by the topology object.](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/2c6c5d6ba61cea9cd1cae8c4acec48759b0cc2aa/wcmp/topology/dcnonly/DCNOnlyTopology.h#L30)

> In general, please consider refactoring gigantic functions into smaller ones. In this case, why not use private functions to generate all individual network element types: s1-s3 switches, links and paths?

Changed into the struct.

> Complexity of finding all direct DCN paths is O(SB_num * SB_num * SB_num * SB_num * 4 * S3_per_MB). I would suggest revising data structures used. Ideally, we want intially to solve only for SB->SB level. So complexity of finding all 1 hop DCN paths should be O(SB_num^2), and complexity of finding all 2 hop paths should be O(SB_num^3).

[Optimized.](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/2c6c5d6ba61cea9cd1cae8c4acec48759b0cc2aa/wcmp/topology/dcnonly/DCNOnlyTopology.cpp#L136)

> Please, refactor this method. Consider one function to create every var, constraint, etc.

[Refactored.](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/2c6c5d6ba61cea9cd1cae8c4acec48759b0cc2aa/wcmp/topology/dcnonly/DCNOnlyTopology.h#L51)

> Maybe also add some experiment or data folder where you can commit data + plots of simulation results? I would suggest do a first set of tests considering time to solution based on number of SBs in the network.

Folder added, experiments will be added soon.

**Comment by duman190** [comment]
Thanks for addressing all of my concerns. I'm closing this.
