### ISSUE TITLE
Milestone 2, review 1

### ISSUE THREAD

**Issue by duman190** [googleinterns/minimal-wcmp-precision-loss#10]
Optimization part only:
================

**LP/ILP Arc Based:**

- Why do we have all LP/ILP solvers in `wcmp/topology/full` path? Maybe move to `wcmp/solver` ? 

- Arc variables should be for every commodity and every link, i.e., for every src->dst pair for every link. The line suggests it is created for every src SB -> dst SB for every link. Why not abstract src->dst pair that can be any?
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/ArcBasedLPSolver.cpp#L36

- When referring to math notations in comments, please, either show full math notation in e.g., corresponding .h file description, or explain in words, e.g., flow conservation constraints:
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/ArcBasedLPSolver.cpp#L53

- This is a fundamental issue here. What if two S3 switches that belong to the same src SB send different amount of traffic?
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/ArcBasedLPSolver.cpp#L69

- I understand the idea of minimizing number of variables for LP behind the introduction of [virtual links and nodes](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/ArcBasedLPSolver.cpp#L150). But it significantly complicates the formulation. Can we just use some arbitrary graph for that as an input, i.e., comprised from virtual nodes and virtual edges? Once, solved, you can map those to your physical switches and links.

- This comment is not consistent with the code:
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/ArcBasedLPSolver.cpp#L222

- Why path id if a flow variable is created for every link?
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/ArcBasedLPSolver.cpp#L346

- What is x, y and b? Please, write more descriptive comments. Please, fix here and everywhere else.
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/ArcBasedILPSolver.cpp#L53
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/ArcBasedILPSolver.cpp#L85
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/ArcBasedILPSolver.cpp#L110

- Why the need for code [duplication](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/ArcBasedILPSolver.cpp#L137)? Can we create LP/ILP solver that either inherit from ArcBasedAbsractSolver or share some SolverUtil API?

- [Same here](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/ArcBasedILPSolver.cpp#L685). Why don't have analysis of solution been separated from solver?

**LP/ILP Path Based:**

- For path formulation, it is similar. What if one path that starts at the same src SB carries more traffic then another one? Current formulation only works for DCN.
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/PathBasedLPSolver.cpp#L37 

- The flow split granularity constraint seems wrong. Why do we use link id if flow variable is for every path?
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/PathBasedILPSolver.cpp#L314

- Code duplication between PathBasedLPSolver and PathBasedILPSolver. Please consider having PathBasedAbstractSolver to share the same code.

- Please, move [analysis](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/PathBasedILPSolver.cpp#L704) of the solution outside of the solver.

**Comment by Clark5** [comment]
> # Optimization part only:
> **LP/ILP Arc Based:**
> 
> * Why do we have all LP/ILP solvers in `wcmp/topology/full` path? Maybe move to `wcmp/solver` ?

The solvers have been moved to wcmp/solver.

> * Arc variables should be for every commodity and every link, i.e., for every src->dst pair for every link. The line suggests it is created for every src SB -> dst SB for every link. Why not abstract src->dst pair that can be any?
>   https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/ArcBasedLPSolver.cpp#L36

The source and destination have been changed at all places and tested. 

> * When referring to math notations in comments, please, either show full math notation in e.g., corresponding .h file description, or explain in words, e.g., flow conservation constraints:
>   https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/ArcBasedLPSolver.cpp#L53

The description comments are added to the constraints and variables. Do you think it is helpful to add a detailed model in PDF form to the repo?

> * This is a fundamental issue here. What if two S3 switches that belong to the same src SB send different amount of traffic?
>   https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/ArcBasedLPSolver.cpp#L69

The only restriction is the amount of traffic going out of the source node is 100%, no force on the equal split of the traffic among S3 switches. 
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/d09946e9ec5dc517eab904f04a3ecd0bc5735d9b/wcmp/solver/ArcBasedLPSolver.cpp#L116-L127

> * I understand the idea of minimizing number of variables for LP behind the introduction of [virtual links and nodes](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/ArcBasedLPSolver.cpp#L150). But it significantly complicates the formulation. Can we just use some arbitrary graph for that as an input, i.e., comprised from virtual nodes and virtual edges? Once, solved, you can map those to your physical switches and links.

The virtual nodes now are used as the source and destination of the traffic, which is much more clear. And different topologies now are defined with different classes.

> * This comment is not consistent with the code:
>   https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/ArcBasedLPSolver.cpp#L222

Changed Comments.
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/34c6bbc45e440b5472286b3ce7e0183d7398d534/wcmp/solver/ArcBasedLPSolver.cpp#L201

> * Why path id if a flow variable is created for every link?
>   https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/ArcBasedLPSolver.cpp#L346

Changed the result analysis function. 

> * What is x, y and b? Please, write more descriptive comments. Please, fix here and everywhere else.
>   https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/ArcBasedILPSolver.cpp#L53
>
>   https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/ArcBasedILPSolver.cpp#L85
>   
>   https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/ArcBasedILPSolver.cpp#L110

Add more comments for the variables.
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/34c6bbc45e440b5472286b3ce7e0183d7398d534/wcmp/solver/ArcBasedILPSolver.cpp#L88-L89

> * Why the need for code [duplication](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/ArcBasedILPSolver.cpp#L137)? Can we create LP/ILP solver that either inherit from ArcBasedAbsractSolver or share some SolverUtil API?

For this part, I keep the current implementation, because the solvers are supposed to independent from each other and can be changed without any dependency. 

> * [Same here](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/ArcBasedILPSolver.cpp#L685). Why don't have analysis of solution been separated from solver?

Split the analysis of the solution from the solvers. 

> **LP/ILP Path Based:**
> 
> * For path formulation, it is similar. What if one path that starts at the same src SB carries more traffic then another one? Current formulation only works for DCN.
>   https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/PathBasedLPSolver.cpp#L37

Now the model is independent of the topology and can be changed by changing the source and destinations switches. 
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/34c6bbc45e440b5472286b3ce7e0183d7398d534/wcmp/solver/PathBasedLPSolver.cpp#L37

> * The flow split granularity constraint seems wrong. Why do we use link id if flow variable is for every path?
>   https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/PathBasedILPSolver.cpp#L314

We use the same strategy as the Arc-based Solver but restricted the maximum hop count to be 2. 

> * Code duplication between PathBasedLPSolver and PathBasedILPSolver. Please consider having PathBasedAbstractSolver to share the same code.

Currently, I didn't merge the code. I can merge it if necessary. 

> * Please, move [analysis](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/PathBasedILPSolver.cpp#L704) of the solution outside of the solver.

Moved outside of the solver. And the analyzer for ILP is WIP.

**Comment by duman190** [comment]
> The description comments are added to the constraints and variables. Do you think it is helpful to add a detailed model in PDF form to the repo?

Yes, please. Improve problem motivation (e.g., by adding some illustrations) as well as add general math formulation for TE path-based model without integer variables. 


> The only restriction is the amount of traffic going out of the source node is 100%, no force on the equal split of the traffic among S3 switches.

The problem is that you aggregated variable per SB. It means that all sources that contribute to the overall SB egress traffic will be treated equally. This problem should be fixed with the transition to the abstract graph input.


> For this part, I keep the current implementation, because the solvers are supposed to independent from each other and can be changed without any dependency.

The difference between ILP and LP is only in extra constraints. No independency is need. In general, please reduce code duplication and work on code refactoring only if time permits.
