### ISSUE TITLE
Milestone 2, review 2

### ISSUE THREAD

**Issue by duman190** [googleinterns/minimal-wcmp-precision-loss#11]
### General:

- Please, add path-based ILP as well:
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/main.cpp#L30

- Please, be consistent with brackets and indents. Check the following 12 lines starting from [here](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/main.cpp#L23).

- I would suggest get rid of S1-S2 scope, and add S2-S3 scope for intra-domain S2 only optimization: https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/definitions.h#L27

- Maybe move `wcmp/unused_components/` to `wcmp/deprecated/` or `wcmp/legacy/`?

- Are there any benefits of using map in proto? For clarity, I would imagine to have one message called, e.g., `TrafficMatrix`, that has repeated field message called, e.g., `TrafficEntry`, and field called `type`. The later, can contain fields such as `source`, `destination` and `traffic`.
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/traffic_trace/trace.proto#L3

- What is the difference between [DCNTopology](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/dcnonly/DCNOnlyTopology.h#L31) and [FullTopology](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/FullTopology.h#L37)? The description in comments for both classes is identical. Please, reduce code duplication.

- Please, rename this class to e.g., `AbstractTopology` and add necessary API once solvers are decoupled and abstracted from the topology.
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/DCN.h#L23

**Comment by Clark5** [comment]
> ### General:
> * Please, add path-based ILP as well:
>   https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/main.cpp#L30

Added. 
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/dd3cdab47139748969514ebe6afee477683e8744/wcmp/main.cpp#L38-L40

> * Please, be consistent with brackets and indents. Check the following 12 lines starting from [here](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/main.cpp#L23).

Changed the indents and brackets.
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/dd3cdab47139748969514ebe6afee477683e8744/wcmp/main.cpp#L16-L23

> * I would suggest get rid of S1-S2 scope, and add S2-S3 scope for intra-domain S2 only optimization: https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/definitions.h#L27

Now the scope has been replaced by the topology, S2-S3 scope will be added soon! As well as the experimental result for it.

> * Maybe move `wcmp/unused_components/` to `wcmp/deprecated/` or `wcmp/legacy/`?

Changed the folder name.

> * Are there any benefits of using map in proto? For clarity, I would imagine to have one message called, e.g., `TrafficMatrix`, that has repeated field message called, e.g., `TrafficEntry`, and field called `type`. The later, can contain fields such as `source`, `destination` and `traffic`.
>   https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/traffic_trace/trace.proto#L3

Easier for the data access and compatible with the data structure used in the main program. So I didn't change this part.  

> * What is the difference between [DCNTopology](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/dcnonly/DCNOnlyTopology.h#L31) and [FullTopology](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/full/FullTopology.h#L37)? The description in comments for both classes is identical. Please, reduce code duplication.

Now those two topologies are different.  

> * Please, rename this class to e.g., `AbstractTopology` and add necessary API once solvers are decoupled and abstracted from the topology.
>   https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/efb133b3d304df10441c87c767e63a6728dd5f76/wcmp/topology/DCN.h#L23

Renamed. And also an "AbstractSolver" class has been added.

**Comment by duman190** [comment]
LGTM. Thanks for addressing all of my concerns. God job!
