### ISSUE TITLE
Milestone 1, review 2: partial review for main.h/cc

### ISSUE THREAD

**Issue by shuoshuc** [googleinterns/minimal-wcmp-precision-loss#2]
1. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/main.h#L17-L18
avoid using macro, use const variables. See https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables.

2. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/main.h#L20-L24
using scoped enum, i.e., enum class, and assign indices for each enum value. Always have an unknown as the first value for fallback safety (unknown = 0). See https://google.github.io/styleguide/cppguide.html#Enumerator_Names

3. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/main.h#L29
Add namespace for every layer of the codebase, including the top level. See https://google.github.io/styleguide/cppguide.html#Namespace_Formatting

4. Usually we only keep a main.cpp as the conventional entry point. You should rename the current main.h to something like definitions.h and only put common declarations/ds types/constants there.

5. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/main.h#L26-L27
Don't see how it's used, consider removing these. For simple functions like this, you should prefer using STL primitives like std::to_string.

6. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/main.cpp#L26
You should always sanity check arguments if you care about them, this goes a long way in preventing stack attacks. Otherwise you should define you main as int main() to avoid taking any parameters.

7. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/main.cpp#L28
For better readability, only use auto when type reduction reduces prolixity or makes code clearer. This is an example for explicit types since it's first time instantiated. See https://google.github.io/styleguide/cppguide.html#Type_deduction

8. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/main.cpp#L31-L32
nit: do it in one line makes it concise.

9. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/main.cpp#L34
Also log the error for debuggability.

10. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/main.cpp#L5-L10
STL header goes before private headers. See https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

11. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/main.cpp#L28
Memroy leak! No in-scope delete! Use std::unique_ptr. See https://google.github.io/styleguide/cppguide.html#Ownership_and_Smart_Pointers

=====================================================================================================
Partial review for main.h/cc. Some comments might overlap with Dmitrii's review 1.

**Comment by Clark5** [comment]
> 1. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/main.h#L17-L18
>   
>    avoid using macro, use const variables. See https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables.

The const variables are used now. 
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/2c6c5d6ba61cea9cd1cae8c4acec48759b0cc2aa/wcmp/definitions.h#L20-L21

> 2. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/main.h#L20-L24
>    
>    using scoped enum, i.e., enum class, and assign indices for each enum value. Always have an unknown as the first value for fallback safety (unknown = 0). See https://google.github.io/styleguide/cppguide.html#Enumerator_Names

Scoped enum is used. 
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/2c6c5d6ba61cea9cd1cae8c4acec48759b0cc2aa/wcmp/definitions.h#L23-L28

> 3. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/main.h#L29
>    
>    Add namespace for every layer of the codebase, including the top level. See https://google.github.io/styleguide/cppguide.html#Namespace_Formatting

Namespace added. 
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/2c6c5d6ba61cea9cd1cae8c4acec48759b0cc2aa/wcmp/definitions.h#L53

> 4. Usually we only keep a main.cpp as the conventional entry point. You should rename the current main.h to something like definitions.h and only put common declarations/ds types/constants there.

File renamed. 
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/2c6c5d6ba61cea9cd1cae8c4acec48759b0cc2aa/wcmp/definitions.h#L53

> 5. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/main.h#L26-L27
>    
>    Don't see how it's used, consider removing these. For simple functions like this, you should prefer using STL primitives like std::to_string.

Changed.

> 6. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/main.cpp#L26
>    
>    You should always sanity check arguments if you care about them, this goes a long way in preventing stack attacks. Otherwise you should define you main as int main() to avoid taking any parameters.

Parameter temporarily removed. 
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/2c6c5d6ba61cea9cd1cae8c4acec48759b0cc2aa/wcmp/main.cpp#L11

> 7. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/main.cpp#L28
>    
>    For better readability, only use auto when type reduction reduces prolixity or makes code clearer. This is an example for explicit types since it's first time instantiated. See https://google.github.io/styleguide/cppguide.html#Type_deduction

Removed the use of auto. Will use type reduction in the future. 

> 8. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/main.cpp#L31-L32
>    
>    nit: do it in one line makes it concise.

Changed. 
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/2c6c5d6ba61cea9cd1cae8c4acec48759b0cc2aa/wcmp/main.cpp#L19

> 9. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/main.cpp#L34
>    
>    Also log the error for debuggability.

Added.
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/2c6c5d6ba61cea9cd1cae8c4acec48759b0cc2aa/wcmp/main.cpp#L20-L22

> 10. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/main.cpp#L5-L10
>     
>     STL header goes before private headers. See https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

Changed all styles in the project.
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/2c6c5d6ba61cea9cd1cae8c4acec48759b0cc2aa/wcmp/main.cpp#L5-L8

> 11. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/main.cpp#L28
>     
>     Memroy leak! No in-scope delete! Use std::unique_ptr. See https://google.github.io/styleguide/cppguide.html#Ownership_and_Smart_Pointers

Removed all the new operations. 
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/2c6c5d6ba61cea9cd1cae8c4acec48759b0cc2aa/wcmp/main.cpp#L16

**Comment by shuoshuc** [comment]
Follow up on #2, pls sort it by enum value, i.e., unknown = 0 goes first.

**Comment by Clark5** [comment]
Sorted the enum value.
