### ISSUE TITLE
Milestone 1, review 3: partial review for components/*

### ISSUE THREAD

**Issue by shuoshuc** [googleinterns/minimal-wcmp-precision-loss#3]
1. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/DCN.h#L16
Don't do this. You should add the project root to your compiler include path, then include headers like #include "traffic_trace/Trace.h".

2. Related to 1, you should use proper project build config, either Makefile, CMakefile or bazel build files, so that others can easily build and run.

3. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/DCN.h#L9-L15
Only include headers where they are directly used. If you only use a function that is used in .cc, include the header file in .cc not in .h

4. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Link.h#L19-L24
Curious do you really need a class? You are using it like a struct. Either switch to struct or make the member variables private and use getter/setter to access them from outside.

5. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Link.h#L18
nit: You need to use auto formatting and proper indentation.

6. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Link.h#L30
Make clear whether copy and move ctors are supported. See https://google.github.io/styleguide/cppguide.html#Copyable_Movable_Types

7. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Link.h#L30
Use std::unique_ptr for pointers everywhere.

8. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Link.h#L30
Use initializer list whenever possible.

9. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Link.h#L21-L23
Be strict about the member variables and their intended use. If they are supposed to be constant, declare them as const.

10. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Link.h#L24
For non-trivial member variables like this, you probably need an explicit dtor.

11. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Link.h#L30
nit: Keep naming consistency, input param should be lower case "id".

12. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Link.cpp#L17
functions should start with a capital letter and have a capital letter for each new word. See https://google.github.io/styleguide/cppguide.html#Function_Names

13. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Link.h#L19-L24
Class member variables should finish with an underscore. See https://google.github.io/styleguide/cppguide.html#Variable_Names

14. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Link.cpp#L13
Insert whitespace properly for string concat.

15. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Path.h#L23
A little confused, does path contain links or vice versa? Why do you need them hold a vector of each other?
Pls add comments to each class definition, explain what they are and the relationship.

16. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Path.cpp#L11-L12
Always use curly brace when for statement takes more than 1 line. Code will fail in bizarre ways when new lines are added since C++ does not operate on indentation.

17. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Path.cpp#L10
Worth re-consider how you want to use these link objs and how you want their life span to be. The raw pointers can be released elsewhere and cause access-after-release errors.

18. related to 17. When you free these heap allocs somewhere, remember to set the points to nullptr explicitly to avoid unsafe access.

19. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Path.cpp#L14
Prefer using std::vector::back().

20. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Path.cpp#L13
Prefer using std:;vector::front().

21. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Path.cpp#L10
Try to avoid duplicate implementation and just call the single link ctor.

22. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Switch.h#L19-L21
Why do you need these integer ids? How are they supposed to be used compared to the name strings?

**Comment by Clark5** [comment]
> 1. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/DCN.h#L16
>    
>    Don't do this. You should add the project root to your compiler include path, then include headers like #include "traffic_trace/Trace.h".

Path added. 
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/2c6c5d6ba61cea9cd1cae8c4acec48759b0cc2aa/wcmp/topology/DCN.h#L13

> 2. Related to 1, you should use proper project build config, either Makefile, CMakefile or bazel build files, so that others can easily build and run.

CMakeLists.txt added. Sorry for missing that file for the previous commit. 

> 3. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/DCN.h#L9-L15
>    
>    Only include headers where they are directly used. If you only use a function that is used in .cc, include the header file in .cc not in .h

Changed all styles in the project.

> 4. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Link.h#L19-L24
>    
>    Curious do you really need a class? You are using it like a struct. Either switch to struct or make the member variables private and use getter/setter to access them from outside.

Changed into the struct.
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/2c6c5d6ba61cea9cd1cae8c4acec48759b0cc2aa/wcmp/definitions.h#L30-L51

> 5. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Link.h#L18
>    
>    nit: You need to use auto formatting and proper indentation.

Format changed. I always use auto-formatting, sorry for the mistake. 

> 6. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Link.h#L30
>    
>    Make clear whether copy and move ctors are supported. See https://google.github.io/styleguide/cppguide.html#Copyable_Movable_Types

Will make it clear in future usage, temporarily removed.

> 7. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Link.h#L30
>    
>    Use std::unique_ptr for pointers everywhere.

Changed. 

> 8. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Link.h#L30
>    
>    Use initializer list whenever possible.

Will use the initializer list in future usage.

> 9. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Link.h#L21-L23
>    
>    Be strict about the member variables and their intended use. If they are supposed to be constant, declare them as const.

Define certain member variables to be const. 
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/2c6c5d6ba61cea9cd1cae8c4acec48759b0cc2aa/wcmp/definitions.h#L30-L51

> 10. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Link.h#L24
>     
>     For non-trivial member variables like this, you probably need an explicit dtor.

dtor for each class will be added soon. 

> 11. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Link.h#L30
>     
>     nit: Keep naming consistency, input param should be lower case "id".

Changed.

> 12. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Link.cpp#L17
>     
>     functions should start with a capital letter and have a capital letter for each new word. See https://google.github.io/styleguide/cppguide.html#Function_Names

All function names changed.

> 13. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Link.h#L19-L24
>     
>     Class member variables should finish with an underscore. See https://google.github.io/styleguide/cppguide.html#Variable_Names

Changed class member variables name. 
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/ff1c8fa2b3bee33e1e524789ec15ffe2437225f1/wcmp/topology/dcnonly/DCNOnlyTopology.h#L28-L40

> 14. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Link.cpp#L13
>     
>     Insert whitespace properly for string concat.

Changed. 

> 15. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Path.h#L23
>     
>     A little confused, does path contain links or vice versa? Why do you need them hold a vector of each other?
>     Pls add comments to each class definition, explain what they are and the relationship.

Class removed.

> 16. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Path.cpp#L11-L12
>     
>     Always use curly brace when for statement takes more than 1 line. Code will fail in bizarre ways when new lines are added since C++ does not operate on indentation.

Changed.

> 17. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Path.cpp#L10
>     
>     Worth re-consider how you want to use these link objs and how you want their life span to be. The raw pointers can be released elsewhere and cause access-after-release errors.

Use data structure in the topology class instead of the Link class. 
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/ff1c8fa2b3bee33e1e524789ec15ffe2437225f1/wcmp/topology/dcnonly/DCNOnlyTopology.h#L38

> 18. related to 17. When you free these heap allocs somewhere, remember to set the points to nullptr explicitly to avoid unsafe access.

Confirmed.

> 19. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Path.cpp#L14
>     
>     Prefer using std::vector::back().

Changed. 

> 20. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Path.cpp#L13
>     
>     Prefer using std:;vector::front().

Changed.

> 21. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Path.cpp#L10
>     
>     Try to avoid duplicate implementation and just call the single link ctor.

File removed.

> 22. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/components/Switch.h#L19-L21
>     
>     Why do you need these integer ids? How are they supposed to be used compared to the name strings?

For future usage, the current topology will not use them.

**Comment by shuoshuc** [comment]
23. nit: I recommend configure your editor to use 2 space as indentation, and auto wrap at 80 characters. It looks like there is some display overflow issue on https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/4cb709e4d2c40ac3cf35436311e6a2627ab38b1a/wcmp/topology/dcnonly/DCNOnlyTopology.cpp#L63

**Comment by Clark5** [comment]
Reformatted all the files with 2 space indent and autowrap at 80 columns.
