### ISSUE TITLE
Milestone 1, review 4: traffic_trace/*

### ISSUE THREAD

**Issue by shuoshuc** [googleinterns/minimal-wcmp-precision-loss#4]
1. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/traffic_trace/Trace.cpp#L8
Put it in the header. One line ctor stays in header.

2. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/traffic_trace/Trace.h#L25-L37
You probably want to cache the matrices to avoid wasted computation and preserve determinism. Additionally you can introduce a param to indicate whether a new matrix should be generated. This won't apply to most of the cases since you are hard coding the matrices.

3. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/traffic_trace/Trace.h#L25-L37
nit: consider implement them as a factory method.

4. As discussed, you need to also implement an import and an export method so that it can be tested with other traffic traces.

**Comment by Clark5** [comment]
> 1. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/traffic_trace/Trace.cpp#L8
>    
>    Put it in the header. One line ctor stays in header.

Moved.
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/ff1c8fa2b3bee33e1e524789ec15ffe2437225f1/wcmp/traffic_trace/Trace.h#L32

> 2. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/traffic_trace/Trace.h#L25-L37
>    
>    You probably want to cache the matrices to avoid wasted computation and preserve determinism. Additionally you can introduce a param to indicate whether a new matrix should be generated. This won't apply to most of the cases since you are hard coding the matrices.

Will be added with the export method. 

> 3. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/5f77edfa1497ecf80469969afdfa7fa24002c884/wcmp/traffic_trace/Trace.h#L25-L37
>    
>    nit: consider implement them as a factory method.

Implemented as a factory method. 
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/ff1c8fa2b3bee33e1e524789ec15ffe2437225f1/wcmp/traffic_trace/Trace.h#L35

> 4. As discussed, you need to also implement an import and an export method so that it can be tested with other traffic traces.

Will be added soon.

**Comment by shuoshuc** [comment]
5. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/4cb709e4d2c40ac3cf35436311e6a2627ab38b1a/wcmp/traffic_trace/Trace.h#L13-L18
another nit: constants and enums usually should be called kSparse/kPermutation etc for easy recognizability.

**Comment by shuoshuc** [comment]
6. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/4cb709e4d2c40ac3cf35436311e6a2627ab38b1a/wcmp/traffic_trace/Trace.cpp#L10
Since std::unordered_map<int, double> is used as a popular type, I suggest giving it a semantic alias like SbDemandMap.

**Comment by Clark5** [comment]
Changed the [enum name](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/b81bdb493893c12e887c1afa24d255cdf2bea82b/wcmp/traffic_trace/Trace.h#L12-L19); set [semantic alias](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/b81bdb493893c12e887c1afa24d255cdf2bea82b/wcmp/traffic_trace/Trace.h#L21) for the popular type

**Comment by shuoshuc** [comment]
6. https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/73c29f069452dde79bae7a5e4045d09e47905644/wcmp/traffic_trace/Trace.h#L21
No, pls use type aliasing in the C++ way:
using SbTrafficMatrix = std::unordered_map<int, double>;
Of course, you will need to add comments about what the int and double are supposed to be, e.g., demand in Gbps.

And you should wrap these classes in namespaces like you did for others.

**Comment by Clark5** [comment]
added the namespace for Trace class; change the typedef into using; comments added. 
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/78ccafdba8d6160f89fe698530eecd980c97f7b3/wcmp/traffic_trace/Trace.h#L23-L25

**Comment by shuoshuc** [comment]
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/78ccafdba8d6160f89fe698530eecd980c97f7b3/wcmp/traffic_trace/Trace.h#L23-L24
If I were to write this comment, it would look like something as follows:
// key is the integer id of a superblock, value is the aggregated egress demand of the corresponding superblock in Gbps.

**Comment by Clark5** [comment]
Changed! Seems like I pushed an incomplete version of comments...
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/6ec490fb50f4b7439ae9c3649ace4dfe8a1f1cfc/wcmp/traffic_trace/Trace.h#L23-L25
