### ISSUE TITLE
Milestone 1, review 5: LP model

### ISSUE THREAD

**Issue by duman190** [googleinterns/minimal-wcmp-precision-loss#5]
- [This constraint](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/2c6c5d6ba61cea9cd1cae8c4acec48759b0cc2aa/wcmp/topology/dcnonly/DCNOnlyTopology.cpp#L256) seems to be wrong. As we do not want to bound mlu at 1, it should be the following:
0 <= u - sum(d/lu * x) <= infinity

- Overall LP model design is biased to DCN only topology. [Here](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/2c6c5d6ba61cea9cd1cae8c4acec48759b0cc2aa/wcmp/topology/dcnonly/DCNOnlyTopology.cpp#L233) is the example of such bias. I would recommend use graph with switches connected with links without mentioning s1/s2/s3 as well as SB ids in the model. Otherwise you will have to create a different LP for different type of topology.

**Comment by Clark5** [comment]
I have changed the constraints function. But for the second comments, I think the current design only follows three principles:
1. Each SuperBlock has multiple MiddleBlocks;
2. Each MiddleBlock has multiple s3 switches;
3. Color sharding for MiddleBlock;
4. The DCN link connects two s3 switches from two SuperBlocks separately. 
I think no additional constraint is introduced though we store the graph with vector structure. 
If you mean that we may build connections between switches other than s3 switches later, then we should change the current representation of the graph.

**Comment by duman190** [comment]
If we are going to solve TE problem for S3->S3 granularity level instead of SB->SB, then [this](https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/2c6c5d6ba61cea9cd1cae8c4acec48759b0cc2aa/wcmp/topology/dcnonly/DCNOnlyTopology.cpp#L233) should be src_s3 / dst_s3, right? If so, please update LP accordingly.

**Comment by Clark5** [comment]
I get your point, so you are saying that the new traffic matrix will be s3->s3 level instead of SB->SB level, right?

**Comment by duman190** [comment]
No, sorry. I meant S1. S1->S1 traffic matrix and paths, i.e., up to 8 hops: S1->S2->S3->S3->S2->S3->S3->S2->S1.

**Comment by Clark5** [comment]
Oh, get it, I will change that in the Milestone 2 codebase.

**Comment by duman190** [comment]
Model is still biased to DCN only topology. Please, fix.

**Comment by Clark5** [comment]
Now I have changed the code structure as well as the solvers, now the solvers are independent from the topology.
