### ISSUE TITLE
Questions for protobuf usage

### ISSUE THREAD

**Issue by Clark5** [googleinterns/minimal-wcmp-precision-loss#6]
Can you give me a pointer to the correct usage of using the map<> in the Protobuf? I cannot find the details in the document. Thanks!  
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/73c29f069452dde79bae7a5e4045d09e47905644/wcmp/traffic_trace/Trace.cpp#L119-L130

**Comment by shuoshuc** [comment]
1. if this section is intended to be export function, you should separate it out like the import function.

2. you can configure github to ignore the proto compiler generated pb files, no need to commit those.

3. protobuf is meant for serialization not a drop-in replacement of standard data structure. I guess you are probably trying to use "repeated"?

**Comment by shuoshuc** [comment]
ah proto3 seems to have added native support for maps (they broke their vow!): https://developers.google.com/protocol-buffers/docs/proto#maps

**Comment by Clark5** [comment]
Get it. I will refer to the example and change the code accordingly.
