### ISSUE TITLE
milestone 1, review 6

### ISSUE THREAD

**Issue by shuoshuc** [googleinterns/minimal-wcmp-precision-loss#7]
https://github.com/googleinterns/minimal-wcmp-precision-loss/blob/54501a5fef293748f969ad5c39683766cff5de6f/wcmp/topology/dcnonly/DCNOnlyTopology.h#L12

nit: you don't have to give each class a namespace. A common practice is to conform to the folder structure, e.g., you can have a top-level namespace called wcmp, and then the traffic trace related stuff falls under wcmp::trace, the topology related stuff goes to wcmp::dcn or wcmp::topology.
You might find https://google.github.io/styleguide/cppguide.html#Namespaces helpful

**Comment by Clark5** [comment]
I have changed the namespace into the folder structure, and derive a namespace hierarchy accordingly.
