### ISSUE TITLE
Milestone 1, review 7

### ISSUE THREAD

**Issue by shuoshuc** [googleinterns/minimal-wcmp-precision-loss#8]
Please update README and include:
1. a high level description of the project.
2. prerequisites, libraries/tools to be installed beforehand. (e.g., SCIP library)
3. instructions on how to compile and run the simulation and where to find the output/results.
4. instructions on how to continue development, e.g., how to bring-your-own-trace, how to bring-your-own-topology.
5. add this line at the bottom of the README: This is not an official Google product.

**Comment by Clark5** [comment]
The README file has been updated as instructed.

**Comment by shuoshuc** [comment]
To compile and run the project, simply follow the instructions:

mkdir build
cd build
cmake ..
make
./wcmp

This won't work. People will git clone and start from the top level directory minimal-wcmp-precision-loss. You cannot just assume everybody starts from wcmp folder. Please fix.

**Comment by shuoshuc** [comment]
Also please be comprehensive on the prerequisites. Have you tested this yourself on a clean ubuntu machine?
At least you would point out that cmake and compiler suites are required. And also maybe point out to the SCIP installation guide and similar for others.

**Comment by shuoshuc** [comment]
This is the error message I got when running cmake:
CMake Error at CMakeLists.txt:9 (find_package):
  By not providing "FindSCIP.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SCIP", but
  CMake did not find one.

  Could not find a package configuration file provided by "SCIP" with any of
  the following names:

    SCIPConfig.cmake
    scip-config.cmake

  Add the installation prefix of "SCIP" to CMAKE_PREFIX_PATH or set
  "SCIP_DIR" to a directory containing one of the above files.  If "SCIP"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!

I think you'll want to be more specific on how to setup the paths in a standard linux commandline dev environment.
